"""Abundance - the encode pass.

Turns the composited PNG sequence into an H.264 mp4 using Blender's own bundled
FFmpeg through the sequencer. (The ffmpeg on PATH here is a broken shim: it
exits 1 and writes nothing, so we do not depend on it.)

  blender -b --factory-startup -P encode.py -- --in comp --out abundance.mp4

Colour: the composited PNGs are already display-referred sRGB. The view
transform MUST be Standard for this pass - leaving it on AgX would apply the
tone map a second time and wash the whole film out.
"""
import bpy, os, sys, glob

HERE = os.path.dirname(os.path.abspath(os.path.realpath(__file__)))
sys.path.insert(0, HERE)
import timeline as T  # noqa: E402

argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []


def arg(name, default=None):
    return argv[argv.index(name) + 1] if name in argv else default


SRC = os.path.abspath(arg("--in", os.path.join(HERE, "comp")))
OUT = os.path.abspath(arg("--out", os.path.join(HERE, "abundance.mp4")))
CRF = arg("--crf", "HIGH")
PCT = int(arg("--pct", "100"))

frames = sorted(glob.glob(os.path.join(SRC, "c_*.png")))
if not frames:
    raise SystemExit("no composited frames in %s" % SRC)

# A gap in the sequence would silently shorten the film, so assert continuity.
nums = [int(os.path.basename(p)[2:7]) for p in frames]
missing = sorted(set(range(nums[0], nums[-1] + 1)) - set(nums))
if missing:
    raise SystemExit("MISSING %d frames, first few: %s" % (len(missing), missing[:12]))
print("frames %d..%d (%d, %.1fs @ %dfps)"
      % (nums[0], nums[-1], len(nums), len(nums) / float(T.FPS), T.FPS))

scn = bpy.context.scene
scn.sequence_editor_create()
scn.render.resolution_x, scn.render.resolution_y = T.W, T.H
scn.render.resolution_percentage = PCT
scn.render.fps = T.FPS
scn.frame_start = 1
scn.frame_end = len(frames)

strip = scn.sequence_editor.sequences.new_image(
    name="abundance", filepath=frames[0], channel=1, frame_start=1)
for p in frames[1:]:
    strip.elements.append(os.path.basename(p))
strip.colorspace_settings.name = "sRGB"

# the frames are already tone-mapped; do not map them again
scn.view_settings.view_transform = "Standard"
scn.view_settings.look = "None"
scn.display_settings.display_device = "sRGB"

scn.render.image_settings.file_format = "FFMPEG"
ff = scn.render.ffmpeg
ff.format = "MPEG4"
ff.codec = "H264"
ff.constant_rate_factor = CRF        # HIGH ~ visually clean at this bitrate
ff.ffmpeg_preset = "GOOD"
ff.gopsize = 15

# Score: generated by broketobuilt scripts/commercial/score-v3.mjs - original
# synthesis, no third-party recordings (the 2026-08-03 Content ID scar).
WAV = arg("--audio", os.path.join(HERE, "score.wav"))
if WAV and os.path.exists(WAV):
    scn.sequence_editor.sequences.new_sound(
        name="score", filepath=os.path.abspath(WAV), channel=2, frame_start=1)
    ff.audio_codec = "AAC"
    ff.audio_bitrate = 192
    ff.audio_mixrate = 48000
    print("audio:", WAV)
else:
    ff.audio_codec = "NONE"
    print("audio: none")
scn.render.filepath = OUT
# without this Blender appends the frame range, e.g. abundance.mp40001-2160.mp4
scn.render.use_file_extension = False

bpy.ops.render.render(animation=True)

if not os.path.exists(OUT):
    # belt and braces: adopt whatever it actually wrote next to our target
    stem = os.path.splitext(os.path.basename(OUT))[0]
    cands = [p for p in glob.glob(os.path.join(os.path.dirname(OUT), stem + "*"))
             if p != OUT and os.path.isfile(p)]
    if cands:
        newest = max(cands, key=os.path.getmtime)
        os.replace(newest, OUT)
        print("adopted", os.path.basename(newest))

if not os.path.exists(OUT):
    raise SystemExit("ENCODE_FAILED: no output at %s" % OUT)
print("ENCODE_DONE -> %s  %.2f MB  %d frames  %.1fs"
      % (OUT, os.path.getsize(OUT) / 1e6, len(frames), len(frames) / float(T.FPS)))
